on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop, qa, master]
name: ci
jobs:
  build-and-push:
    name: Build & Push image
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        ref: develop
    - name: Login to Docker Hub ${{ secrets.DOCKERHUB_USERNAME }}
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      with:
        images: noglaxmanapp/noglaxman-backend
    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/noglaxman-backend:${{ github.ref_name }}-${{ github.sha }}
